### ISSUE TITLE
upcoming events indicator will not show across multiple months of upcoming events

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.tuesdaystunes.tv#106]
Currently the Upcoming Events list is designed to show an upcoming event indicator ( 👈 ) to indicate the next future event.
![Image](https://user-images.githubusercontent.com/895923/206874051-edb76906-e79e-4510-9976-f43289e31b32.png)

Unfortunately in the code, I think it will only handle indicators in the _current_ month, due to the hardcoded `0`.
https://github.com/AnalogStudiosRI/www.tuesdaystunes.tv/blob/main/src/components/upcoming-events/upcoming-events.js#L77
```js
```

What I think will happen if you have this upcoming schedule
**This Month**
1. Date 12
1. Date 26 👈 

**Next Month**
1. Date 12

If a user comes onto the site _after_ the 26th (but before it is **Next Month**) I think the indicator would just disappear, or just be stuck on the second event in **This Month**.

What it should come out as is
**This Month**
1. Date 12
1. Date 26 

**Next Month**
1. Date 12 👈

**Comment by adrianmarinwork** [comment]
I can take care of this issue if you want!

**Comment by thescientist13** [comment]
Thank you!  Let me know if you have any questions.

**Comment by bjcreal** [comment]
Hi @thescientist13, I smoothed out the next upcoming event indicator logic and fixed this bug in the pull request linked above. First-time contributor here so let me know if I'm missing anything!

**Comment by adrianmarinwork** [comment]
Looks like @bjcreal has taken care of the issue, check his pull request!

**Comment by thescientist13** [comment]
Thank you both of you for wanting to help out!

@bjcreal 
Did a quick glance but will dive in a little deeper to test in a couple days, thanks for the PR!  🙏 

@adrianmarinwork 
Let me know if any other issues catch your eye, even if not a good first issue, depending on what you're up for and if I can articulate well enough (😅 ) would love your help on the project!  💯
