### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.tuesdaystunes.tv#11]
## Overview
Create the Footer component.
![Image](https://user-images.githubusercontent.com/895923/188248610-9ec771dd-5264-4ba0-8c70-7cc50d462048.png)

Links
* YouTube - https://www.youtube.com/user/analogstudios
* Facebook - https://www.facebook.com/Tuesdays-Tunes-111968014950570
* Spotify - https://open.spotify.com/playlist/1jOFrovuxCGulkGdUhR5f7

## Requirements
1. [ ] Component
1. [ ] Storybook
1. [ ] Spec

> _Does **not** need to handle the page "tear" effect_, will [likely become part of the main page (template)](https://github.com/AnalogStudiosRI/www.tuesdaystunes.tv/issues/21#issuecomment-1272380826)

**Comment by VedanthB** [comment]
Can i work on this

**Comment by thescientist13** [comment]
Sure, this should be good to start on now!  Just know that some of the styles and colors will come in once #13 is done (it is in progress currently) but you can definitely start with getting the HTML and Storybook work ready for this component.  👍

**Comment by VedanthB** [comment]
Can I work on this

**Comment by thevinitgupta** [comment]
Can I start working on this?

**Comment by thescientist13** [comment]
Hey @thevinitgupta and @VedanthB , thanks for reaching out on this !

Just an update that  I'll be working on the project this weekend trying to get the first version ready for the Tuesday's Tunes season premier this Tuesday, so definitely happy to have contributions along the way!  Feel free to [join our Slack in the **#tuesdays-tunes-dev** channel](https://join.slack.com/t/thegreenhouseio/shared_invite/enQtMzcyMzE2Mjk1MjgwLTU5YmM1MDJiMTg0ODk4MjA4NzUwNWFmZmMxNDY5MTcwM2I0MjYxN2VhOTEwNDU2YWQwOWQzZmY1YzY4MWRlOGI) and I'll be in there happy to help with guiding contributions since things might be moving fast the next few days.

Will keep you posted on status of this feature either way and there are other features to assist with as well.  Happy to help find ways to help folks contribute to OSS, and since it October, maybe even a free t-shirt.  😎
