### ISSUE TITLE
Theme and Styleguide

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.tuesdaystunes.tv#13]
## Overview
Capture the theme and style guide as CSS custom properties.  Should also include figuring out how to achieve the "tearing" effect for the top and bottom of the page.

<img width="801" alt="Screen Shot 2022-10-02 at 3 02 04 PM" src="https://user-images.githubusercontent.com/895923/193471493-4f67ffe8-8e93-44f7-9b83-6ecf3dcb9e41.png">

## Requirements
1. [ ] CSS Variable for color and fonts
1. [ ] Styleguide documented in Storybook

**Comment by rashmisubhash** [comment]
Can I give this a try?

**Comment by thescientist13** [comment]
That would be great, thanks!  🙌

**Comment by rashmisubhash** [comment]
Can you please give me a little more context what needs to be done here

**Comment by thescientist13** [comment]
Sure!  

If you want to start with https://github.com/AnalogStudiosRI/www.tuesdaystunes.tv/discussions/3 it should give a bit of a higher level overview of the website but the TLDR is that for now just focusing on a "brochure" style site with Header, Upcoming Show details, playlists, etc all kind of stacked up one on top of the other.  (The designs currently show multiple pages so that and the navigation will be changed in the next iteration).

So this issue is to just layout the ground work a little bit by getting the project setup with the colors, fonts, and basic layout out of the home page.  Actual component development will happen as part of other tasks.  The repo also comes with Storybook setup to help facilitate that sort of isolated development and so then by the end, all these components can be combined to create the Home page.

Also, I have a [Slack workspace (**#tuesdays-tunes-dev**)](https://join.slack.com/t/thegreenhouseio/shared_invite/enQtMzcyMzE2Mjk1MjgwLTU5YmM1MDJiMTg0ODk4MjA4NzUwNWFmZmMxNDY5MTcwM2I0MjYxN2VhOTEwNDU2YWQwOWQzZmY1YzY4MWRlOGI) if you want to join to ask any questions.  Thanks!

**Comment by rashmisubhash** [comment]
I can work on the header and footer to start with

**Comment by thescientist13** [comment]
Thanks!  I think it would be good to start here with just getting the fonts and colors in place first, since all components and pages will at least need that at least.

Could just start with a _styles/theme.css_ and pull all our variables and global styles / fonts etc in there and then `@import` that into _main.css_.  That should then update in both Storybook and _index.html_.  👍 

From there, once that is look good, we can merge a PR for that and then I think footer is a good next choice!  (header designs are still a bit of a WIP).

**Comment by rashmisubhash** [comment]
Alright, I was just working on the header, I will pause it for now and focus on the theme

![image](https://user-images.githubusercontent.com/29196787/188293771-d145941f-c13c-44e5-a8c5-828485f5728e.png)

**Comment by thescientist13** [comment]
That's a great start and thank you!

I know that part of the design will change once I have the new design revision to make the site more brochure like, which will remove most, if not all of the navigation.  Plus the logo will be positioned a little differently.  Just want to help you avoid re-doing any work ideally.

Once the next design revision comes in I can update the details of that issue and definitely you can feel free to work on it.  👍
