### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.tuesdaystunes.tv#14]
## Overview
Create the Header component w/ navigation.

<img width="794" alt="Screen Shot 2022-10-08 at 2 17 23 PM" src="https://user-images.githubusercontent.com/895923/194721896-61101665-6ebb-454b-8596-5a9fdd2a3cc1.png">

Some notes:
1. Would use stacked header logo (will work on getting an actual image from the designer, can just do a screen grab for now)
1. **_No_** navigation needed in header for now, page will just use vertical scrolling and there is only this page.

> _Would be nice to achieve the "tearing"  design, not sure if it [should be in the header or as part of the top of the home page](https://github.com/AnalogStudiosRI/www.tuesdaystunes.tv/issues/21#issuecomment-1272380826)?  We will have actual links soon to a couple other pages, then the navigation would be inside that tearing effect, so leaning towards yes?_  🤔 

## Requirements
1. [ ] Component
1. [ ] Storybook
1. [ ] Spec

**Comment by VedanthB** [comment]
I'd like to give this a try.

**Comment by thescientist13** [comment]
Hey @VedanthB , thanks for reaching out!  This issue isn't quite ready yet, and apologies on my end for mis-labeling.   But please feel free to see if any of the other `help wanted` issues are of interest to you and let me know if you have any questions.
