### ISSUE TITLE
Youtube Playlist

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.tuesdaystunes.tv#17]
## Overview
Create a component to embed the Tuesday's Tunes YouTube playlist.
https://www.youtube.com/watch?v=qRskZcB5Rbc&list=PLrY8SmqJ5XZ_UvVurEvGg8i10g-cxMudZ&ab_channel=AnalogStudiosRI

![Image](https://user-images.githubusercontent.com/895923/188249593-da02b1d5-3e89-474e-8c02-ec843a6ca97f.png)

## Requirements
1. [ ] Embed playlist into a component
1. [ ] Storybook
1. [ ] Spec
1. [ ] Try and have most recent episode show up first
1. [ ] See if we can theme it

**Comment by Omafovbe** [comment]
Hi, Please I would love to take this challenge and work on this issue. Thanks

**Comment by thescientist13** [comment]
That would be great thanks!

**Comment by Omafovbe** [comment]
Thanks, would get on it and send a PR accordingly.

**Comment by thescientist13** [comment]
Hey @Omafovbe  , thanks for reaching out on this !

Just an update that  I'll be working on the project this weekend trying to get the first version ready for the Tuesday's Tunes season premier this Tuesday, so definitely happy to have contributions along the way!  Feel free to [join our Slack in the **#tuesdays-tunes-dev** channel](https://join.slack.com/t/thegreenhouseio/shared_invite/enQtMzcyMzE2Mjk1MjgwLTU5YmM1MDJiMTg0ODk4MjA4NzUwNWFmZmMxNDY5MTcwM2I0MjYxN2VhOTEwNDU2YWQwOWQzZmY1YzY4MWRlOGI) and I'll be in there happy to help with guiding contributions since things might be moving fast the next few days.

Will keep you posted on status of this feature either way and there are other features to assist with as well.  Happy to help find ways to help folks contribute to OSS, and since it October, maybe even a free t-shirt.  😎

**Comment by Omafovbe** [comment]
Hi,

Sorry for the delay but surely you will get the update later today. And
thanks for the opportunity.
