### ISSUE TITLE
Spotify Playlist

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.tuesdaystunes.tv#18]
## Overview
Create a component for embedding the Tuesday's Tunes Spotify playlist.
https://open.spotify.com/playlist/1jOFrovuxCGulkGdUhR5f7?si=R1ZowQxqSRefj6HLOasSEQ&nd=1
![Image](https://user-images.githubusercontent.com/895923/188249724-8ba0175b-11c6-42d1-a8a8-2456729635de.png)

## Requirements
https://artists.spotify.com/en/help/article/embedded-players
1. [ ] Embed the Spotify Playlist Episode Information
1. [ ] Storybook
1. [ ] Spec
1. [ ] Try and have most recent songs show up first
1. [ ] See if we can theme it

**Comment by Mshehu5** [comment]
Hey, can I work on this ?
Would like to make a contribution

**Comment by thescientist13** [comment]
Sure @Mshehu5 !

I would take a look at the existing Footer component and try and use that as a base to build up a Spotify playlist web component.  I would use Storybook for your development so you can work on it an isolated manner.

Check the README and CONTRIBUTING docs and let me know if you have any questions!

**Comment by thescientist13** [comment]
Hey @Mshehu5  , thanks for reaching out on this !

Just an update that  I'll be working on the project this weekend trying to get the first version ready for the Tuesday's Tunes season premier this Tuesday, so definitely happy to have contributions along the way!  Feel free to [join our Slack in the **#tuesdays-tunes-dev** channel](https://join.slack.com/t/thegreenhouseio/shared_invite/enQtMzcyMzE2Mjk1MjgwLTU5YmM1MDJiMTg0ODk4MjA4NzUwNWFmZmMxNDY5MTcwM2I0MjYxN2VhOTEwNDU2YWQwOWQzZmY1YzY4MWRlOGI) and I'll be in there happy to help with guiding contributions since things might be moving fast the next few days.

Will keep you posted on status of this feature either way and there are other features to assist with as well.  Happy to help find ways to help folks contribute to OSS, and since it October, maybe even a free t-shirt.  😎

**Comment by aholtzman** [comment]
@thescientist13 do you want to start with embedding the iframe for the playlist as a first step and then later explore using their api to make a more custom component? Styling limitations and order would be impacted from the original concept/design.

**Comment by thescientist13** [comment]
Yeah, it's fine to just start with an `<iframe>` embed for now to get something going, even if we lose a bit of control.  I think we're considering that for you YouTube player for now as well - https://github.com/AnalogStudiosRI/www.tuesdaystunes.tv/pull/36#discussion_r990845303.

Do you know if Spotify APIs can be used client side?  We could pre-render a list of songs at build time, but then if content change (songs added / removed / etc) I wonder if there is a web hook that Spotify could send us to let us know to rebuild?  Or could we just fetch the songs on the client side?  Either way, good to know our options, to help me evaluate the best data fetching / rendering strategy for the project for dynamic data (events, Spotify, YouTube)
