### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.tuesdaystunes.tv#21]
## Overview
This is a list of all the things we want to have on the home page, in approximate order.  Linked tickets capture most of the components needed to create it, so those can / should be worked on first.

<img width="1003" alt="Screen Shot 2022-10-08 at 2 32 50 PM" src="https://user-images.githubusercontent.com/895923/194722390-f0a170ba-3826-4c83-a167-3a4013ecf4fd.png">

## Sections / Integrations
1. [ ] Page "tearing" design
1. [x] #14 
1. [x] #16 
1. [ ] About TT
1. [ ] #18 
1. [x] #17 
1. [x] #11 
1. [x] Favicon - https://github.com/AnalogStudiosRI/www.tuesdaystunes.tv/pull/42

> _Depends on #15 and #20_

## Nice To Have
1. [ ] #19
1. [ ] Styled Scrollbar
1. [ ] intersection observers for the playlists, or can just use `loading="lazy"`?

**Comment by thevinitgupta** [comment]
Is there any of the tasks available to work on?

**Comment by thescientist13** [comment]
Hey @thevinitgupta.  Yeah, some of these tasks should be available to work on, and would be [labelled with _good first issue_](https://github.com/AnalogStudiosRI/www.tuesdaystunes.tv/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).  Will cross-link here in the description as well.

Also, shared a little [status update here](); just to keep you up to date.  👍

**Comment by thevinitgupta** [comment]
@thescientist13 I would love to work on the page tearing design.
Could you create a separate issue explaining what are the features needed to be implemented and assign me to the issue?

**Comment by thescientist13** [comment]
Yeah, if you want to give that a try, the main requirement is just achieving the effect from the designs where the content section will have the top and bottom "tearing effect" to it, that blends into a white background for the content itself, and then ends before the footer.

So I think from the HTML perspective, it would look something like
```html
 <tt-header></tt-header>
<main>
  <!-- page content goes here -->
</main>
<tt-footer></tt-footer>
```

I think the header is probably the best place to put the top section, and then page (`<main>`) can manage the bottom tear.  I can assign #14 to you if you want to start with the top part?  Or I can assign you this ticket if you want to work on the bottom part.

CSS and design are not my strength, so open to other thoughts and approaches on approaching this as well.  👍
