### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.tuesdaystunes.tv#28]
## Overview
Create the Navigation component w/ menu.

<img width="726" alt="Screen Shot 2022-10-08 at 2 41 12 PM" src="https://user-images.githubusercontent.com/895923/194722720-1a26448f-0286-4473-907e-b3859d21f233.png">

## Requirements
1. [ ] Component
1. [ ] Storybook
1. [ ] Spec

**Comment by aholtzman** [comment]
I will get a PR up for a starter skeleton for this shortly.
