### ISSUE TITLE
Add standards colors to styleguide and apply to project

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.tuesdaystunes.tv#34]
As part of #13, forgot to include the gray, black, and white (neutral) colors to the palette, that is being used throughout [the designs](https://drive.google.com/drive/u/0/folders/1fxFZpeW4VUmZbvfqR2Q_Um9zAT6-iBnI), which you can see popping up in the PRs for #30 and #31.

It would be good to:
1. [ ] Capture the value of gray from the designs, plus white (`#efefef`) and black (`#020202`) that we need as a CSS custom property in _theme.css_
1. [ ] Document it in Storybook
1. [ ] Replace Tailwind instances of `gray-text-500`, `rgba(107, 114, 128)`,  etc or otherwise "Tailwindify" them
1. [ ] (nice to have) Apply gray color to footer SVG icons

**Comment by aholtzman** [comment]
I can put up a PR for this shortly.
