### ISSUE TITLE
styled scrollbar

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.tuesdaystunes.tv#54]
Not sure if it is possible, but per the designs, the scrollbar should be the color of the accent color from the Styleguide (`--color-accent`).

![Image](https://user-images.githubusercontent.com/895923/197582044-9de89443-ba0c-4d70-b474-bbba9f6c31a7.png)

**Comment by KaptainCS3** [comment]
!assign

**Comment by thescientist13** [comment]
Done @KaptainCS3 ! 🙌
